### ISSUE TITLE
[BUG] IOS Build Error.

### ISSUE THREAD

**Issue by NakiriYuuzu** [Tlaster/PreCompose#342]
**Describe the bug**
Using Precompose 1.6.0 is working fine, but when I upgrade to 1.6.1 get this Build Error.
```
Failed to load native library:libjansi.jnilib. The native library file at .gradle/native/jansi/1.18/osx/libjansi.jnilib is not executable, make sure that the directory is mounted on a partition without the noexec flag, or set the jansi.tmpdir system property to point to a proper location.  osinfo: Mac/arm64

w: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: ComposeApp. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.
e: Compilation failed: Exception during generating code for following declaration:
Inside: FILE fqName:<root>
Inside: CLASS OBJECT name:ComposableSingletons$AppKt modality:FINAL visibility:internal superTypes:[]
@Composable
private fun <init>$lambda$8$lambda$7$lambda$6($navigator: Navigator, /* var */ $composer: Composer?, $changed: Int) {
  $init_global()
  var $composer: Composer? = $composer
  when {
    when {
      areEqualByValue(first = $changed.and(other = 11).reinterpret<Int, Int>(), second = 2.reinterpret<Int, Int>()).not() -> true
      true -> $composer.<get-skipping>().not()
    } -> { // BLOCK
      Navigation(navigator = $navigator, $composer = $composer, $changed = #moe_tlaster_precompose_navigation_Navigator$stable)
    }
    true -> $composer.skipToGroupEnd()
  }
  return theUnitInstance()
}


Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: ComposeApp. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.

 * Source files: 
 * Compiler version: 2.0.0
 * Output kind: FRAMEWORK
```

**To Reproduce**
1. Run on apple device.

**Comment by Tlaster** [comment]
Seems like we're on board with the same issue: https://github.com/JetBrains/compose-multiplatform/issues/4809#issuecomment-2169302897

**Comment by N7ghtm4r3** [comment]
Sorry, the solution for this error is to apply:
`kotlin.native.cacheKind=none` property
 to `gradle.properties` file like said
[here](https://github.com/JetBrains/compose-multiplatform/issues/4809#issuecomment-2210806903)
