### ISSUE TITLE
Support compose 1.5.0-dev1114

### ISSUE THREAD

**Issue by QiXi** [Tlaster/PreCompose#73]
After I updated dependency compose.version=1.5.0-dev1104 to 1.5.0-dev1114

I am getting an error during execution

> Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 
> 'void androidx.compose.animation.AnimatedContentKt.AnimatedContent(Object, Modifier, Function1, Alignment, String, Function4, Composer, int, int)'
> 	at moe.tlaster.precompose.navigation.NavHostKt.NavHost(NavHost.kt:135)

Plan for compatibility with the latest version of compose. Your library helps me a lot, thanks.

**Comment by qdsfdhvh** [comment]
`compose-multiplatform 1.5.0` may not be released for a while, I've uploaded a `SNAPSHOT` version as a temporary fix.

```kotlin
maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")

implementation("io.github.qdsfdhvh:precompose:1.4.5-SNAPSHOT")
```

**Comment by QiXi** [comment]
I have import problems 

> import moe.tlaster.precompose.`viewmodel`.ViewModel
> import moe.tlaster.precompose.`viewmodel`.viewModelScope

**Comment by QiXi** [comment]
i checked now everything works with `compose.version=1.5.0-dev1122`
